<?php
return [
    'Airlines (US)' => [
        'NASDAQ:AAL' => 'American Airlines (AAL)',
        'NYSE:DAL' => 'Delta Air Lines (DAL)',
        'NASDAQ:UAL' => 'United Airlines (UAL)',
        'NYSE:LUV' => 'Southwest (LUV)',
        'NASDAQ:JBLU' => 'JetBlue (JBLU)',
        'NYSE:ALK' => 'Alaska Air (ALK)',
        'NYSE:FLYY' => 'Spirit (FLYY)',
        'NASDAQ:ULCC' => 'Frontier (ULCC)',
        'NASDAQ:ALGT' => 'Allegiant (ALGT)',
        'NASDAQ:SKYW' => 'SkyWest (SKYW)',
        'NASDAQ:MESA' => 'Mesa Air (MESA)',
        'NASDAQ:SNCY' => 'Sun Country Airlines (SNCY)',
    ],
    'Airlines (Canada/LatAm)' => [
        'TSX:AC' => 'Air Canada (AC)',
        'NYSE:VLRS' => 'Volaris (VLRS)',
        'OTC:AZULQ' => 'Azul (AZULQ)',
        'NYSE:GOL' => 'GOL (GOL)',
        'NYSE:CPA' => 'Copa (CPA)',
        'SNSE:LTM' => 'LATAM (LTM)',
        'NYSE:AVH' => 'Avianca (AVH)',
    ],
    'Airlines (Europe)' => [
        'LSE:IAG' => 'IAG (IAG)',
        'XETRA:LHA' => 'Lufthansa (LHA)',
        'EPA:AF' => 'Air France-KLM (AF)',
        'NASDAQ:RYAAY' => 'Ryanair ADR (RYAAY)',
        'LSE:EZJ' => 'easyJet (EZJ)',
        'LSE:WIZZ' => 'Wizz Air (WIZZ)',
        'LSE:JET2' => 'Jet2 (JET2)',
        'LSE:TUI' => 'TUI (TUI)',
        'OSE:NAS' => 'Norwegian (NAS)',
        'BIST:PGSUS' => 'Pegasus Airlines (PGSUS)',
    ],
    'Airlines (APAC)' => [
        'TSE:9202' => 'ANA Holdings (9202)',
        'TSE:9201' => 'Japan Airlines (9201)',
        'SGX:C6L' => 'Singapore Airlines (C6L)',
        'HKEX:0293' => 'Cathay Pacific (0293)',
        'KRX:003490' => 'Korean Air (003490)',
        'KRX:020560' => 'Asiana (020560)',
        'ASX:QAN' => 'Qantas (QAN)',
        'NZX:AIR' => 'Air New Zealand (AIR)',
        'NSE:INDIGO' => 'IndiGo (INDIGO)',
        'NSE:SPICEJET' => 'SpiceJet (SPICEJET)',
        'HKEX:0753' => 'Air China (0753)',
        'HKEX:1055' => 'China Southern Airlines (1055)',
        'HKEX:0670' => 'China Eastern Airlines (0670)',
    ],
    'Hotels' => [
        'NASDAQ:MAR' => 'Marriott (MAR)',
        'NYSE:HLT' => 'Hilton (HLT)',
        'NYSE:H' => 'Hyatt (H)',
        'NYSE:IHG' => 'IHG (IHG)',
        'NYSE:CHH' => 'Choice (CHH)',
        'NYSE:WH' => 'Wyndham (WH)',
        'EPA:AC' => 'Accor (AC)',
        'HKEX:0069' => 'Shangri-La Asia (0069)',
        'BME:MEL' => 'Meliá Hotels (MEL)',
        'NASDAQ:HTHT' => 'H World Group (HTHT)',
        'NASDAQ:ATAT' => 'Atour Lifestyle Holdings (ATAT)',
    ],
    'OTAs/Platforms' => [
        'NASDAQ:BKNG' => 'Booking Holdings (BKNG)',
        'NASDAQ:EXPE' => 'Expedia (EXPE)',
        'NASDAQ:TCOM' => 'Trip.com Group (TCOM)',
        'NASDAQ:TRIP' => 'Tripadvisor (TRIP)',
        'NASDAQ:TRVG' => 'trivago (TRVG)',
        'NASDAQ:ABNB' => 'Airbnb (ABNB)',
        'NASDAQ:MMYT' => 'MakeMyTrip (MMYT)',
        'NYSE:DESP' => 'Despegar (DESP)',
        'BME:EDR' => 'eDreams ODIGEO (EDR)',
        'NYSE:TNL' => 'Travel + Leisure Co. (TNL)',
    ],
    'GDS/Travel Tech' => [
        'NASDAQ:SABR' => 'Sabre (SABR)',
        'BME:AMS' => 'Amadeus IT (AMS)',
        'NASDAQ:PROS' => 'PROS Holdings (PROS)',
    ],
    'Airports/Operators' => [
        'BME:AENA' => 'Aena (AENA)',
        'ETR:FRA' => 'Fraport (FRA)',
        'EPA:ADP' => 'Groupe ADP (ADP)',
        'NYSE:ASR' => 'Grupo Aeroportuario del Sureste (ASR)',
        'NYSE:PAC' => 'Grupo Aeroportuario del Pacífico (PAC)',
        'NASDAQ:OMAB' => 'Grupo Aeroportuario del Centro Norte (OMAB)',
    ],
    'Payments/Banks (Cards & Points)' => [
        'NYSE:V' => 'Visa (V)',
        'NYSE:MA' => 'Mastercard (MA)',
        'NYSE:AXP' => 'American Express (AXP)',
        'NYSE:DFS' => 'Discover (DFS)',
        'NYSE:COF' => 'Capital One (COF)',
        'NYSE:JPM' => 'JPMorgan Chase (JPM)',
        'NYSE:C' => 'Citi (C)',
        'NYSE:BAC' => 'Bank of America (BAC)',
        'NYSE:WFC' => 'Wells Fargo (WFC)',
        'NYSE:USB' => 'U.S. Bank (USB)',
        'NYSE:BCS' => 'Barclays (BCS)',
        'NYSE:GS' => 'Goldman Sachs (GS)',
        'NYSE:SYF' => 'Synchrony Financial (SYF)',
    ],
    'Cruise Lines' => [
        'NYSE:CCL' => 'Carnival (CCL)',
        'NYSE:RCL' => 'Royal Caribbean (RCL)',
        'NYSE:NCLH' => 'Norwegian Cruise Line (NCLH)',
    ],
    'Car Rentals' => [
        'NASDAQ:HTZ' => 'Hertz (HTZ)',
        'NASDAQ:CAR' => 'Avis Budget Group (CAR)',
    ],
];
