<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"
                xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
                exclude-result-prefixes="sitemap news image">
<xsl:output method="html" encoding="UTF-8" indent="yes"/>

<xsl:template match="/">
    <html>
        <head>
            <title>News XML Sitemap</title>
            <style type="text/css">
                body {
                    font-family: sans-serif;
                    background-color: #fff;
                    color: #333;
                }
                #content {
                    max-width: 1200px;
                    margin: 2em auto;
                    padding: 0 1em;
                }
                h1 {
                    font-size: 24px;
                    font-weight: 600;
                    padding-bottom: 0.5em;
                    border-bottom: 1px solid #ddd;
                }
                p {
                    font-size: 14px;
                }
                a {
                    color: #48991E;
                    text-decoration: none;
                }
                a:hover {
                    text-decoration: underline;
                }
                table {
                    width: 100%;
                    border-collapse: collapse;
                    margin-top: 1.5em;
                    font-size: 13px;
                }
                th, td {
                    text-align: left;
                    padding: 0.25em 0.8em;
                    border-bottom: 1px solid #eee;
                }
                thead th {
                    background-color: #f9f9f9;
                    font-weight: 600;
                }
                tbody tr:hover {
                    background-color: #f5f5f5;
                }
                td {
                    vertical-align: middle; /* CHANGED: Adjusted vertical alignment for a cleaner look */
                }
                .url-cell {
                    word-break: break-all;
                }
                img {
                    max-width: 70px;      /* CHANGED: Reduced image size */
                    max-height: 35px;     /* CHANGED: Reduced image size */
                    border: 1px solid #ddd;
                    border-radius: 4px;
                    vertical-align: middle; /* This helps the image align with the text */
                }
                .empty-message {
                    margin-top: 1.5em;
                    padding: 1em;
                    background-color: #f9f9f9;
                    border-left: 4px solid #48991E;
                }
            </style>
        </head>
        <body>
            <div id="content">
                <h1>News XML Sitemap</h1>
                <p>Generated by <strong><a href="https://boardingarea.com/">BoardingArea</a></strong>, this is a News XML Sitemap, meant for consumption by search engines.</p>
                <p>You can find more information about XML sitemaps on <strong><a href="https://sitemaps.org">sitemaps.org</a></strong>.</p>

                <xsl:choose>
                    <xsl:when test="count(sitemap:urlset/sitemap:url) > 0">
                        <p>This News XML Sitemap contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> articles.</p>
                        <table>
                            <thead>
                                <tr>
                                    <th style="width: 8%;">Image</th>
                                    <th style="width: 27%;">URL</th>
                                    <th style="width: 25%;">Article Title</th>
                                    <th style="width: 10%;">Keywords</th>
                                    <th style="width: 10%;">Genres</th>
                                    <th style="width: 10%;">Publication Date</th>
                                    <th style="width: 10%;">Last Modified</th>
                                </tr>
                            </thead>
                            <tbody>
                                <xsl:for-each select="sitemap:urlset/sitemap:url">
                                    <tr>
                                        <td>
                                            <xsl:if test="image:image/image:loc">
                                                <img src="{image:image/image:loc}" alt="Featured Image" />
                                            </xsl:if>
                                        </td>
                                        <td class="url-cell">
                                            <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
                                        </td>
                                        <td>
                                            <xsl:value-of select="news:news/news:title"/>
                                        </td>
                                        <td>
                                            <xsl:value-of select="news:news/news:keywords"/>
                                        </td>
                                        <td>
                                            <xsl:value-of select="news:news/news:genres"/>
                                        </td>
                                        <td>
                                            <xsl:value-of select="news:news/news:publication_date"/>
                                        </td>
                                        <td>
                                            <xsl:value-of select="sitemap:lastmod"/>
                                        </td>
                                    </tr>
                                </xsl:for-each>
                            </tbody>
                        </table>
                    </xsl:when>
                    <xsl:otherwise>
                        <p class="empty-message">No articles have been published in the last 48 hours.</p>
                    </xsl:otherwise>
                </xsl:choose>
            </div>
        </body>
    </html>
</xsl:template>
</xsl:stylesheet>
